export const LINING_TYPES = [
  {
    id: 'full',
    label: 'Full Lining',
    description: 'Classic full interior lining. Provides structure, easy to put on, professional finish.',
    diagramImageUrl: '/images/lining/full-lining-diagram.png',
  },
  {
    id: 'half',
    label: 'Half Lining',
    description: 'Lined only at the back and sleeves. Cooler, breathable — ideal for summer suits.',
    diagramImageUrl: '/images/lining/half-lining-diagram.png',
  },
];

export const LINING_COLORS = [
  { id: 'navy', name: 'Navy Blue', hexCode: '#1B3A6B', swatchImageUrl: '/images/lining/colors/navy.jpg', isCupra: false },
  { id: 'charcoal', name: 'Charcoal', hexCode: '#36454F', swatchImageUrl: '/images/lining/colors/charcoal.jpg', isCupra: false },
  { id: 'black', name: 'Black', hexCode: '#1C1C1C', swatchImageUrl: '/images/lining/colors/black.jpg', isCupra: false },
  { id: 'ivory', name: 'Ivory', hexCode: '#FFFFF0', swatchImageUrl: '/images/lining/colors/ivory.jpg', isCupra: false },
  { id: 'burgundy', name: 'Burgundy', hexCode: '#800020', swatchImageUrl: '/images/lining/colors/burgundy.jpg', isCupra: false },
  { id: 'royal-blue', name: 'Royal Blue', hexCode: '#4169E1', swatchImageUrl: '/images/lining/colors/royal-blue.jpg', isCupra: false },
  { id: 'forest-green', name: 'Forest Green', hexCode: '#228B22', swatchImageUrl: '/images/lining/colors/forest-green.jpg', isCupra: false },
  { id: 'camel', name: 'Camel', hexCode: '#C19A6B', swatchImageUrl: '/images/lining/colors/camel.jpg', isCupra: false },
  { id: 'silver', name: 'Silver', hexCode: '#C0C0C0', swatchImageUrl: '/images/lining/colors/silver.jpg', isCupra: false },
  { id: 'gold', name: 'Gold', hexCode: '#FFD700', swatchImageUrl: '/images/lining/colors/gold.jpg', isCupra: false },
  { id: 'crimson', name: 'Crimson', hexCode: '#DC143C', swatchImageUrl: '/images/lining/colors/crimson.jpg', isCupra: false },
  { id: 'teal', name: 'Teal', hexCode: '#008080', swatchImageUrl: '/images/lining/colors/teal.jpg', isCupra: false },
  { id: 'purple', name: 'Purple', hexCode: '#800080', swatchImageUrl: '/images/lining/colors/purple.jpg', isCupra: false },
  { id: 'coral', name: 'Coral', hexCode: '#FF7F50', swatchImageUrl: '/images/lining/colors/coral.jpg', isCupra: false },
  { id: 'slate', name: 'Slate Blue', hexCode: '#6A7FAB', swatchImageUrl: '/images/lining/colors/slate.jpg', isCupra: false },
  { id: 'olive', name: 'Olive', hexCode: '#808000', swatchImageUrl: '/images/lining/colors/olive.jpg', isCupra: false },
  { id: 'mustard', name: 'Mustard', hexCode: '#FFDB58', swatchImageUrl: '/images/lining/colors/mustard.jpg', isCupra: false },
  { id: 'rose', name: 'Rose Pink', hexCode: '#FF007F', swatchImageUrl: '/images/lining/colors/rose.jpg', isCupra: false },
  { id: 'sand', name: 'Sand', hexCode: '#F4A460', swatchImageUrl: '/images/lining/colors/sand.jpg', isCupra: false },
  { id: 'midnight', name: 'Midnight Blue', hexCode: '#191970', swatchImageUrl: '/images/lining/colors/midnight.jpg', isCupra: false },
  { id: 'wine', name: 'Wine', hexCode: '#722F37', swatchImageUrl: '/images/lining/colors/wine.jpg', isCupra: false },
  { id: 'sky', name: 'Sky Blue', hexCode: '#87CEEB', swatchImageUrl: '/images/lining/colors/sky.jpg', isCupra: false },
  { id: 'emerald', name: 'Emerald', hexCode: '#50C878', swatchImageUrl: '/images/lining/colors/emerald.jpg', isCupra: false },
  { id: 'taupe', name: 'Taupe', hexCode: '#483C32', swatchImageUrl: '/images/lining/colors/taupe.jpg', isCupra: false },
  { id: 'champagne', name: 'Champagne', hexCode: '#F7E7CE', swatchImageUrl: '/images/lining/colors/champagne.jpg', isCupra: false },
  { id: 'steel', name: 'Steel Blue', hexCode: '#4682B4', swatchImageUrl: '/images/lining/colors/steel.jpg', isCupra: false },
  { id: 'amber', name: 'Amber', hexCode: '#FFBF00', swatchImageUrl: '/images/lining/colors/amber.jpg', isCupra: false },
  { id: 'plum', name: 'Plum', hexCode: '#DDA0DD', swatchImageUrl: '/images/lining/colors/plum.jpg', isCupra: false },
  { id: 'cupra-black', name: 'CUPRA Black', hexCode: '#0D0D0D', swatchImageUrl: '/images/lining/colors/cupra-black.jpg', isCupra: true },
  { id: 'cupra-ivory', name: 'CUPRA Ivory', hexCode: '#FEFEFA', swatchImageUrl: '/images/lining/colors/cupra-ivory.jpg', isCupra: true },
  { id: 'cupra-navy', name: 'CUPRA Navy', hexCode: '#0A1931', swatchImageUrl: '/images/lining/colors/cupra-navy.jpg', isCupra: true },
];

export const LINING_PATTERNS = [
  { id: 'paisley', name: 'Paisley', swatchImageUrl: '/images/lining/patterns/paisley.jpg', description: 'Classic teardrop motif — elegant and traditional.' },
  { id: 'stripes', name: 'Thin Stripes', swatchImageUrl: '/images/lining/patterns/stripes.jpg', description: 'Subtle pinstripes for a business-formal look.' },
  { id: 'polka-dots', name: 'Polka Dots', swatchImageUrl: '/images/lining/patterns/polka-dots.jpg', description: 'Playful and retro. A fun hidden detail.' },
  { id: 'floral', name: 'Floral', swatchImageUrl: '/images/lining/patterns/floral.jpg', description: 'Delicate floral prints for a romantic touch.' },
  { id: 'geometric', name: 'Geometric', swatchImageUrl: '/images/lining/patterns/geometric.jpg', description: 'Modern angular patterns for a contemporary look.' },
  { id: 'houndstooth', name: 'Houndstooth', swatchImageUrl: '/images/lining/patterns/houndstooth.jpg', description: 'Classic British check pattern.' },
  { id: 'herringbone', name: 'Herringbone', swatchImageUrl: '/images/lining/patterns/herringbone.jpg', description: 'V-shaped weave — timeless and sophisticated.' },
  { id: 'plaid', name: 'Plaid', swatchImageUrl: '/images/lining/patterns/plaid.jpg', description: 'Tartan-inspired grid pattern.' },
  { id: 'damask', name: 'Damask', swatchImageUrl: '/images/lining/patterns/damask.jpg', description: 'Ornate woven pattern — luxurious and rich.' },
  { id: 'abstract', name: 'Abstract', swatchImageUrl: '/images/lining/patterns/abstract.jpg', description: 'Modern artistic swirls for the bold dresser.' },
  { id: 'anchor', name: 'Nautical Anchor', swatchImageUrl: '/images/lining/patterns/anchor.jpg', description: 'Nautical theme — a great conversation starter.' },
];
